# Generated by Django 5.0 on 2024-02-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('year_types', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=20)),
                ('branch_types', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Biotechnology', 'Biotechnology'), ('Information Technology', 'Information Technology'), ('Automobile Engineering', 'Automobile Engineering')], max_length=50)),
                ('Password', models.CharField(max_length=255)),
                ('Confirm_password', models.CharField(max_length=255)),
            ],
        ),
    ]
