# Generated by Django 5.0 on 2024-02-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_rename_confirm_password_signin_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='Confirmpassword',
            new_name='Confirm_password',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='password',
            new_name='Password',
        ),
    ]
