# Generated by Django 5.0 on 2024-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0010_alter_signin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
