# Generated by Django 5.0 on 2024-02-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0011_alter_signin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='branch_types',
            new_name='branch_type',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='year_types',
            new_name='year_type',
        ),
    ]
