# Generated by Django 5.0 on 2024-02-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0012_rename_branch_types_signin_branch_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='branch_type',
            new_name='branch_types',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='year_type',
            new_name='year_types',
        ),
    ]
