# Generated by Django 5.0 on 2024-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0013_rename_branch_type_signin_branch_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
