# Generated by Django 5.0 on 2024-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('professor', 'Professor'), ('Associate professor', 'Associate Professor'), ('Assistant professor', 'Assintant Professor')], max_length=50),
        ),
    ]
