# Generated by Django 5.0 on 2024-03-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0002_alter_faculty_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE(Regular)', 'CSE(Regular)'), ('CSE(HONORS)', 'CSE(HONORS)'), ('CSIT', 'CSIT')], max_length=50),
        ),
    ]
