# Generated by Django 5.0 on 2024-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0004_facultycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='coursecode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='facultyid',
            field=models.BigIntegerField(),
        ),
    ]
