# Generated by Django 5.0 on 2024-03-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0005_alter_facultycourse_coursecode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultycourse',
            old_name='coursecode',
            new_name='courseid',
        ),
    ]
