# Generated by Django 5.0 on 2024-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0006_rename_coursecode_facultycourse_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='courseid',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
