# Generated by Django 5.0 on 2024-03-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0008_facultycourse_facultyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycourse',
            name='facultyname',
        ),
    ]
