# Generated by Django 5.0 on 2024-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0009_remove_facultycourse_facultyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='facultyid',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(unique=True, max_length=255),  # Adjust max_length as needed
        ),
    ]
