# Generated by Django 5.0 on 2024-03-09 22:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0011_alter_faculty_facultyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='courseid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
