# Generated by Django 5.0 on 2024-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0012_alter_facultycourse_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='courseid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
