# Generated by Django 5.0 on 2024-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0013_alter_facultycourse_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facultyid',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='facultyid',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
