# Generated by Django 5.0 on 2024-03-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0014_alter_faculty_facultyid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemodule.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemodule.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemodule.student')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
    ]
