# Generated by Django 5.0 on 2024-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodule', '0015_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='courseid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='facultyid',
            field=models.BigIntegerField(),
        ),
    ]
